import os
import asyncio
from video_processor import VideoProcessor

def test_script_to_video():
    print("Testing Script to Video...")
    p = VideoProcessor()

    script = "Hello world. This is a test video generated by AI CapCut. It mimics the script to video feature."

    # We can't easily test TTS without network or api key sometimes, but edge-tts is free.
    # We will try running it.
    try:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        path = loop.run_until_complete(p.generate_script_video(script))
        print(f"Generated video at: {path}")
        if os.path.exists(path):
            print("SUCCESS: File exists.")
        else:
            print("FAILURE: File not found.")
    except Exception as e:
        print(f"Error in Script to Video: {e}")

def test_timeline_render():
    print("Testing Timeline Render...")
    p = VideoProcessor()

    # Create dummy assets
    # Blue image
    from PIL import Image
    img = Image.new('RGB', (100, 100), color = 'blue')
    img.save("test_blue.jpg")

    timeline = {
        "format": {"width": 640, "height": 360, "fps": 24},
        "tracks": [
            {
                "type": "video",
                "clips": [
                    {"type": "text", "content": "Intro", "duration": 2, "position": 0, "color": "red"},
                    {"type": "image", "source": "test_blue.jpg", "duration": 2, "position": 2},
                    {"type": "text", "content": "End", "duration": 2, "position": 4, "color": "green"}
                ]
            }
        ]
    }

    try:
        path = p.render_timeline(timeline, "test_timeline.mp4")
        print(f"Rendered timeline at: {path}")
        if os.path.exists(path):
            print("SUCCESS: Timeline video exists.")
        else:
            print("FAILURE: Timeline video not found.")
    except Exception as e:
        print(f"Error in Timeline Render: {e}")

if __name__ == "__main__":
    test_timeline_render()
    # test_script_to_video() # Uncomment if we want to test edge-tts (might be slow or blocked)
